# Generated by Django 4.2.4 on 2023-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='AJDM', max_length=255),
        ),
    ]
