# Generated by Django 4.2.4 on 2023-08-07 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal_crud_app', '0002_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='q_one',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='q_three',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='q_two',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
