# Generated by Django 4.2.4 on 2023-08-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_crud_app', '0003_remove_book_inventory_remove_book_price_book_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Journal',
        ),
    ]
