# Generated by Django 4.2.4 on 2023-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_crud_app', '0004_rename_book_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
