# Generated by Django 4.2.4 on 2023-08-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_crud_app', '0005_alter_journal_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='created',
            new_name='date_created',
        ),
    ]
