# Generated by Django 4.2.4 on 2023-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_crud_app', '0006_rename_created_journal_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
